FROM debian:buster-slim

RUN apt-get update \
 && apt-get install -y \
    git curl wget netcat \
    build-essential

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=$PATH:/usr/local/cargo/bin
ARG RUST_VERSION=1.40.0
RUN wget https://static.rust-lang.org/rustup/archive/1.21.1/x86_64-unknown-linux-gnu/rustup-init -O rustup-init \
 && chmod +x rustup-init \
 && ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION \
 && rm rustup-init

ARG LIBRESPOT_REF=b634117fbfa550d4280ac951be9cb1d8183d2c99

RUN git clone https://github.com/librespot-org/librespot /librespot \
 && cd /librespot && git checkout $LIBRESPOT_REF \
 && cargo build --no-default-features \
 && cp target/debug/librespot /usr/bin/librespot

COPY librespot.sh /librespot.sh

CMD ["/librespot.sh"]
